# Generated by Django 4.2 on 2023-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
